export const NOTE = {
    CREATE: 'CREATE_NOTE',
    UPDATE:'UPDATE_NOTE',
    DELETE: 'DELETE_NOTE',
    CHANGE: 'CHANGE_CURRENT_MENU',
    POPULATE: "POPULATE_NOTE"
}

export const WEB = {
    SIGN_UP: "SIGN_UP",
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",

    SAVE: "SAVE_NOTES",
    SHOW_ERROR: "SHOW_ERROR",
    HIDE_ERROR: 'HIDE_ERROR'
}
